[package]
name = "scratchpost"
version = "0.1.0"
edition = "2021"
description = "A simple key/value cache server built in Rust."
license = "MIT"

[dependencies]
queues = "1.1.0"

[dependencies.rocket]
version = "0.5.1"
features = ["json"]
